### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by digitarald** [devtools-html/devtools-html.github.com#15]
I'd use Cloudflare [1] if there are no better ideas [2].

[1]: https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc
[2]: https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8

**Comment by wkillerud** [comment]
[Recent events](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) should make this easier with just standard Github Pages options.

> If you are using `CNAME` or `ALIAS` records for your custom domain, you’re all set and your site should be accessible over HTTPS. If it is, and your site loads correctly over HTTPS, [you can optionally enforce HTTPS in your repository’s settings](https://help.github.com/articles/securing-your-github-pages-site-with-https/). Users who request your site over HTTP will be upgraded to HTTPS.
>
> If you are using `A` records, you must update your site’s DNS records with new IP addresses. Please [see our guide to setting up your custom domain with Pages and update any `A` records you might have set.](https://help.github.com/articles/setting-up-an-apex-domain/)
>
> Once your updated DNS records have propagated, and you’ve confirmed that your site loads correctly over HTTPS, you can optionally “[Enforce HTTPS](https://help.github.com/articles/securing-your-github-pages-site-with-https/)” for your domain in your repository’s settings, ensuring users who request your site over HTTP are upgraded to HTTPS.

Visiting https://firefox-dev.tools/ today gives a certificate error, so unfortunately some action needs to be taken :frowning_face: 

```
The certificate is only valid for the following names: 
*.github.com, github.com, *.github.io, github.io
```

**Comment by captainbrosset** [comment]
This was done. Our 3 sites all support https now:

https://firefox-dev.tools/
https://docs.firefox-dev.tools/
https://bugs.firefox-dev.tools/
